/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fk_prof_InstrumentationStub */

#ifndef _Included_fk_prof_InstrumentationStub
#define _Included_fk_prof_InstrumentationStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fk_prof_InstrumentationStub
 * Method:    evtReturn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fk_prof_InstrumentationStub_evtReturn
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
