#!/bin/bash
set -x

PAC=load-gen-app
CMD="$1"

USER=fk-prof-nfr
GROUP=fk-prof-nfr

USER_ID=9876
GID=9876

if [ "$1" == "configure" ] ; then

    #creating user if it doesnt exist
    if ! getent group $GROUP > /dev/null; then
        groupadd -g $GID $GROUP
    fi

    if ! getent passwd $USER_ID > /dev/null; then
        adduser --system --uid $USER_ID --home /usr/share/$PAC --no-create-home \
        --ingroup $GROUP --disabled-password --shell /bin/false \
        $USER
    fi

    #configure the app from ansible and then start
fi

# log folder
mkdir -p /var/log/load-gen-app

ln -s /etc/sv/load-gen-app.svc /etc/service/
chown -R $USER:$GROUP /var/log/load-gen-app /etc/sv/load-gen-app.svc /etc/load-gen-app /usr/share/load-gen-app
chmod 744 /usr/share/load-gen-app/*

exit 0
