#!/bin/bash
set -x

PAC=load-gen-app
CMD="$1"

USER=fk-prof
GROUP=fk-prof-dev

USER_ID=6015
GID=6030

if [ "$1" == "configure" ] ; then

    #creating user if it doesnt exist
    if ! getent group $GROUP > /dev/null; then
        groupadd -g $GID $GROUP
    fi

    if ! getent passwd $USER_ID > /dev/null; then
        adduser --system --uid $USER_ID --home /usr/share/$PAC --no-create-home \
        --ingroup $GROUP --disabled-password --shell /bin/false \
        $USER
    fi

	echo "Starting $PAC service"
	#start the svc
  
fi

exit 0
