/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fk_prof_recorder_main_JniBurn */

#ifndef _Included_fk_prof_recorder_main_JniBurn
#define _Included_fk_prof_recorder_main_JniBurn
#ifdef __cplusplus
extern "C" {
#endif
#undef fk_prof_recorder_main_JniBurn_MULTIPLIER
#define fk_prof_recorder_main_JniBurn_MULTIPLIER 10000L
/*
 * Class:     fk_prof_recorder_main_JniBurn
 * Method:    jniBurn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fk_prof_recorder_main_JniBurn_jniBurn
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
